apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
    <head>
    <title>Deuuu bommmmm !!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Salveee salve ! Task concluida com sucesso  =) !!</h1>
    <p>Ta destruindo d+ parabens !!!</p>



    <p><em>By P0ssuidao.</em></p>
    </body>
    </html>


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: indexsite
  namespace: web
