apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: webserver-service
  namespace: web
spec:
  ports:
  # por padrão o targerport é defenido como mesmo valor de port
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-template
  type: NodePort
